SELECT A.AUTHOR_ID,A.AUTHOR_NAME,C.CATEGORY, C.TOTAL_SALES FROM AUTHOR A
JOIN (SELECT B.AUTHOR_ID AS AUTHOR_ID, B.CATEGORY AS CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID=S.BOOK_ID
WHERE YEAR(S.SALES_DATE)=2022 AND MONTH(S.SALES_DATE)=1
GROUP BY B.AUTHOR_ID,B.CATEGORY)C
ON A.AUTHOR_ID=C.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, C.CATEGORY DESC