SELECT  A. AUTHOR_ID, A.AUTHOR_NAME,C.CATEGORY, SUM(C.PRICE*C.SALES) AS TOTAL_SALES FROM AUTHOR A
RIGHT JOIN (SELECT B.BOOK_ID,
        B.AUTHOR_ID,
        B.PRICE,
        B.CATEGORY,
        S.SALES,
        S.SALES_DATE FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID=S.BOOK_ID
WHERE YEAR(S.SALES_DATE)='2022' AND MONTH(S.SALES_DATE)='01')C
ON A.AUTHOR_ID=C.AUTHOR_ID
GROUP BY A.AUTHOR_ID, C.CATEGORY
ORDER BY A.AUTHOR_ID ASC,C.CATEGORY DESC;