SELECT ID,
    CASE 
        WHEN GROUP_NUM=1 THEN 'CRITICAL'
        WHEN GROUP_NUM=2 THEN 'HIGH'
        WHEN GROUP_NUM=3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM(
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GROUP_NUM
    FROM ECOLI_DATA) AS T
ORDER BY ID ASC;
    