SELECT
    ID,
    CASE 
        WHEN COLONY_ID=1 THEN 'CRITICAL'
        WHEN COLONY_ID=2 THEN 'HIGH'
        WHEN COLONY_ID=3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM(
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_ID
    FROM ECOLI_DATA
)AS T
ORDER BY ID ASC;