SELECT ID,
    CASE
        WHEN P<=0.25 THEN 'CRITICAL'
        WHEN P<=0.5 THEN 'HIGH'
        WHEN P<=0.75 THEN 'MEDIUM'
        WHEN P<=1 THEN 'LOW'
    END AS COLONY_NAME
FROM
(SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS P FROM ECOLI_DATA)AS S
ORDER BY ID;