SELECT 
    DATE_FORMAT(B.SALES_DATE,'%Y') AS YEAR,
    DATE_FORMAT(B.SALES_DATE,'%m') AS MONTH,
    A.GENDER,
    COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE B
JOIN USER_INFO A ON B.USER_ID=A.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, A.GENDER
ORDER BY YEAR,MONTH,A.GENDER ASC;