SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_FORMAT
FROM MEMBER_PROFILE
WHERE 1=1
 AND MONTH(DATE_OF_BIRTH)=3 
 AND TLNO != "" 
 AND GENDER = "W"
ORDER BY MEMBER_ID ASC;