SELECT 
    A.USER_ID,
    A.NICKNAME,
    SUM(CASE WHEN B.STATUS = 'DONE' THEN B.PRICE ELSE 0 END) AS TOTAL_SALES
FROM USED_GOODS_USER A
JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
GROUP BY A.USER_ID, A.NICKNAME
HAVING SUM(CASE WHEN B.STATUS = 'DONE' THEN B.PRICE ELSE 0 END) >= 700000
ORDER BY SUM(CASE WHEN B.STATUS = 'DONE' THEN B.PRICE ELSE 0 END) ASC;
