SELECT A.MEMBER_NAME,B.REVIEW_TEXT,DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE 
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B
ON B.MEMBER_ID=A.MEMBER_ID
WHERE B.MEMBER_ID=(SELECT B.MEMBER_ID
FROM REST_REVIEW B
GROUP BY B.MEMBER_ID
ORDER BY COUNT(B.MEMBER_ID) DESC LIMIT 1)
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;
