SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID=B.MEMBER_ID
WHERE A.MEMBER_NAME
=(SELECT A.MEMBER_NAME FROM MEMBER_PROFILE A
 JOIN REST_REVIEW B ON A.MEMBER_ID=B.MEMBER_ID
 GROUP BY A.MEMBER_NAME
 ORDER BY COUNT(*) DESC LIMIT 1)
 ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;