WITH FILTERED AS (
    SELECT 
        CAR_ID, 
        MONTH(START_DATE) AS MONTH,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID, MONTH(START_DATE)
),
CAR_TOTAL AS (
    SELECT CAR_ID
    FROM FILTERED
    GROUP BY CAR_ID
    HAVING SUM(RECORDS) >= 5
)
SELECT 
    F.MONTH, 
    F.CAR_ID, 
    F.RECORDS
FROM FILTERED F
JOIN CAR_TOTAL C ON F.CAR_ID = C.CAR_ID
ORDER BY F.MONTH ASC, F.CAR_ID DESC;
