SELECT B.CATEGORY, B.PRICE AS MAX_PRICE, B.PRODUCT_NAME FROM FOOD_PRODUCT B
JOIN 
(SELECT CATEGORY,MAX(PRICE) AS P FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY)A
ON B.CATEGORY=A.CATEGORY
WHERE B.CATEGORY=A.CATEGORY AND A.P=B.PRICE
ORDER BY B.PRICE DESC;